### PR TITLE
Flailing attempt to address #991

### PR DESCRIPTION
**Pull request by manez**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/991

# What does this Pull Request do?

I'm not sure if I came at this correctly at all, but I tried to follow the instructions Danny left in https://github.com/Islandora-CLAW/CLAW/issues/991 and added descriptions I got from http://files.archivists.org/pubs/DACS2E-2013_v0315.pdf where they were missing from our existing taxonomies.

# What's new?

New descriptions on:

* Person
* Geographic Location
* Subject
* Family

# How should this be tested?

Pull in the changes and check that the new descriptions show up and are correct. I used http://files.archivists.org/pubs/DACS2E-2013_v0315.pdf at a reference. 

# Additional Notes:
I think this is my first Islandora CLAW PR that does not involve a mascot 😸 

# Interested parties
@dannylamb or @seth-shaw-unlv I suppose?

### CODE REVIEW

**Comment by mjordan** [comment]
Checked out this branch, went to `admin/config/development/features/diff` and imported changes to the "Controlled Access Terms default configuration". The import showed success, but the descriptions are not showing up at `admin/structure/taxonomy`. Maybe I'm not testing this correctly?

**Comment by seth-shaw-unlv** [comment]
@mjordan did you clear cache?

**Comment by dannylamb** [comment]
@manez `An individual of the human species.`++

**Comment by seth-shaw-unlv** [comment]
@mjordan weird, it isn't updating for me either. I see no discernable difference between corporate_body (which does have a working description) and family (or any of the other new ones) that would cause it to fail. I'm even doing a clean enable of the module and it isn't picking up the new descriptions.

**Comment by dannylamb** [comment]
@manez Given the issues @seth-shaw-unlv and @mjordan are having, I'll wait until they can get it working before merging.

**Comment by mjordan** [comment]
@seth-shaw-unlv I didn't but when I just started up the VM now, @manez changes are appearing, so, without a better explanation as to why they are there, I'll chock it up to a cache issue.

**Comment by seth-shaw-unlv** [comment]
@dannylamb & @mjordan, it must have been some weird caching issue for me too. I did a fresh DrupalVM, composer require, and then applied the PR. That worked fine. Go ahead and merge it.

**Pull request merged**
