### PR TITLE
Remove config from module

### PR DESCRIPTION
**Pull request by whikloj**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/902

Related PR: https://github.com/Islandora-CLAW/islandora/pull/98

This PR removes the configuration and moves it to a feature in the Islandora module (above PR).

See there for more information.

@seth-shaw-unlv @Islandora-CLAW/committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Oh, yeah, forgot about those.

**Comment by seth-shaw-unlv** [comment]
I must have applied the PR incorrectly... it doesn't make sense why that error should appear.

**Comment by seth-shaw-unlv** [comment]
@whikloj probably. Although I haven't seen @Natkeeran around today, so we might have to wait unless someone else wants to click the merge button.

**Comment by seth-shaw-unlv** [comment]
@whikloj once that schema config is merged this PR should pull it over into the new feature submodule.

While we are at it, could we add "Controlled Access Terms" to the sub-module name in [info.yml](https://github.com/Islandora-CLAW/controlled_access_terms/pull/6/files#diff-1d45ce3465072125b236e6ab6f8bb126R1)? Thanks.

**Comment by dannylamb** [comment]
Superseded by https://github.com/Islandora-CLAW/controlled_access_terms/commit/66bab1aaa32c5773ea2d003e94cc4e8509313fe1

**Pull request closed without merging**
